--- 
alert: false
analytics: 
  enabled: false
  google_analytics: 
    enabled: false
    tracking_id: UA-1234567
author: "Guillaume Arseneault"
bootstrap: 
  css: bootstrap.css
  js: 
    enabled: true
    src: bootstrap.min.js
  responsive: 
    css: bootstrap-responsive.min.css
    enabled: true
brand: gllmAr
description: "reinjection cinétique interactive  kinectic feedback"
disqus: 
  enabled: false
  shortname: myshortname
  show_comment_count: true
email: guillaume.arseneault@gmail.com
exclude: 
  - README.md
  - version.txt
external_links: 
  header: Hyperliens
  links: 
    - 
      link: ~
      name: Artificiel
      url: "http://artificiel.org"
    - 
      link: ~
      name: Gllm-Vimeo
      url: "https://vimeo.com/arseninc/videos"
favicon: 
  enabled: true
  local: 
    enabled: false
    partial_url: false
    type: png
  remote: 
    enabled: true
    full_url: "https://dl.dropboxusercontent.com/u/15569938/git/gllmar.github.com/img/gllm-favicon.png"
    type: png
font_awesome: 
  css: font-awesome.min.css
  enabled: true
github_projects: 
  - 
    project: 
      name: Bulles
      url: "https://github.com/gllmar/bulles-prog"
jquery: 
  enabled: true
  src: jquery-1.9.1.min.js
markdown: kramdown
name: "Guillaume Arseneault"
navbar: 
  archive: 
    enabled: true
  categories: 
    enabled: true
  external_links: 
    enabled: false
  github_projects: 
    enabled: true
  social_links: 
    enabled: false
  tags: 
    enabled: true
notice: false
paginate: 10
rss: 
  enabled: true
  image: 
    enabled: false
    image: false
  managing_editor: 
    enabled: false
    managing_editor: false
  ttl: 
    enabled: true
    ttl: 300
  webmaster: 
    enabled: false
    webmaster: false
sections: 
  archive: 
    enabled: false
  brief_bio: 
    content: 
      enabled: true
    enabled: true
    github_projects: 
      enabled: true
    image: 
      enabled: false
      url: false
    social_links: 
      enabled: false
  categories: 
    enabled: false
  external_links: 
    enabled: true
  github_projects: 
    enabled: false
  social_links: 
    enabled: false
  tags: 
    enabled: false
social_links: 
  follow_name: Me
  links: 
    - 
      enabled: false
      font_awesome_icon: icon-facebook
      link: ~
      name: Facebook
      url: "https://www.facebook.com/"
    - 
      enabled: true
      font_awesome_icon: icon-github-alt
      link: ~
      name: GitHub
      url: "https://github.com/gllmar"
    - 
      enabled: false
      font_awesome_icon: icon-google-plus
      link: ~
      name: Google+
      url: "https://plus.google.com/"
    - 
      enabled: false
      font_awesome_icon: icon-linkedin
      link: ~
      name: Linkedin
      url: "http://www.linkedin.com/"
    - 
      enabled: false
      font_awesome_icon: icon-pinterest
      link: ~
      name: Pinterest
      url: "http://www.pinterest.com"
    - 
      enabled: true
      font_awesome_icon: icon-twitter
      link: ~
      name: Twitter
      url: "https://www.twitter.com/arsenog"
syntax_highlighting: 
  css: syntax.css
  enabled: true
url: "https://gllmar.github.io"
